### PR TITLE
Update CoTeTo and Mapclasses

### PR DESCRIPTION
**Pull request by carlesRT**
- Changes to work with more than one file (	98b32a5 and aeb1e49)

- Some of the new modules in 8182d37 are probably now not used. but.. the more the better.

Important points which it is necessary to have  a closer look are:

- There is an attribut missing... Program was not working so i did some provisional changes. (914ca79)

- Have a look at 4d6c403. The program was crashing because `UnboundLocalError: local variable 'sim_port_in' referenced before assignment`. In this case the program was dealing with `child[id]:  <SimModel_Hierachy.SimHierarchyNode; proxy of <Swig Object of type 'std::vector< SimHierarchyNode * >::value_type' at 0x0B2B82F0> >  of the type:  SimDistributionPort_HotWaterFlowPort_Water_In`. The program was working with `SimDistributionPort_HotWaterFlowPort_Water_Out` without problems...

### CODE REVIEW

**Comment by thorade** [comment]
@PRemmen Do we want to merge this into development or into SimModel_Python_API_v2.2 ??
And can we merge some recent working version into the master please?
So that we can start fresh branches from the master

**Comment by PRemmen** [comment]
@thorade @carlesRT I would prefer merging it into development because in development everything for python is rather up to date (I will push latest release from @math-boy from last evening).

No objections to merge development into master

**Comment by math-boy** [comment]
@PRemmen In my last update, I enabled the rule filter for property One2One, and refined its function.  This part is working stable now. Therefore, today I will work on enabling the filter for property Transfromation , and testing it on the rules. There will be another update later today. So I would suggest u directly merge my code until my next release today. I will let you know when the release is online.

**Comment by thorade** [comment]
OK, so Peter merges Juns latest code into `development`,
then Carles has to update his Pull Request,
then we merge Carles code into development,
then we merge development into master.

After that, everybody should branch from the latest master!

**Comment by carlesRT** [comment]
ok.

**Comment by thorade** [comment]
Maybe we can also merge some of the other branches into master?
https://github.com/EnEff-BIM/EnEffBIM-Framework/branches/all

**Comment by math-boy** [comment]
@thorade @carlesRT @PRemmen Just a hint for you: My last update in yesterday is not a stable version, I still need to do some further testing on an mapping rule filter for the data Transformation rule. If you r using the code of the last update, you will find the data Transformation rule yet is not working. I will enable this rule filter after today's testing and code revising.

**Pull request closed without merging**
